import type { Lang } from "./data.ts";

/** Arayüz metinleri. İçerik (görevler, belgeler) data.ts içindedir. */
const COPY = {
  tr: {
    htmlTitle: "Murat Can Başkan — Uzakyol Baş Mühendisi | bskn.tr",
    description:
      "Murat Can Başkan, Uzakyol Baş Mühendisi. 2007’den beri tanker, dökme yük, capesize, Ro-Ro ve yüzer santrallerde makine dairesi; ME-B ve ME-C yeni inşa teslimleri.",
    ogTitle: "Murat Can Başkan — Uzakyol Baş Mühendisi",
    skip: "İçeriğe geç",
    nav: { career: "Kariyer", fleet: "Filo", skills: "Uzmanlık", credentials: "Belgeler", contact: "İletişim" },
    navLabel: "Bölümler",
    langLabel: "Dil seçimi",
    themeToDark: "Koyu temaya geç",
    themeToLight: "Açık temaya geç",
    cv: "CV indir",
    cvLong: "CV indir — PDF (İngilizce)",
    heroKicker: "Uzakyol Baş Mühendisi · İTÜ Denizcilik YDO’06",
    heroLead: (years: number, posts: number) =>
      `${years} yıldır makine dairesinde. Ürün tankerinden capesize’a, buhar türbininden ME-C’ye — ${posts} görev, tek disiplin.`,
    heroCareer: "Kariyeri gör",
    currentLabel: "Güncel görev",
    statsLabel: "Rakamlarla",
    bmmsKicker: "Bugün üzerinde çalıştığım proje",
    bmmsLink: "BMMS tanıtım sayfası",
    careerKicker: "Sefer defteri",
    careerTitle: (start: number) => `${start}’den bugüne`,
    careerHint: "Gemi tipine göre süz.",
    filterLabel: "Gemi tipine göre süz",
    now: "Şu an",
    shown: (n: number) => `${n} görev gösteriliyor`,
    fleetKicker: "Filo",
    fleetTitle: "Çalışılan gemi ve tesis tipleri",
    skillsKicker: "Uzmanlık",
    skillsTitle: "Makine dairesinin istedikleri",
    credKicker: "Belgeler",
    credTitle: "Sertifikalar ve eğitimler",
    pending: "Sertifika bekleniyor",
    memberTitle: "Üyelikler",
    eduTitle: "Eğitim",
    langTitle: "Diller",
    contactKicker: "İletişim",
    contactTitle: "Bir sonraki sefer için konuşalım.",
    contactSub: "Görev, danışmanlık ve teknik iş birlikleri için.",
    phone: "Telefon",
    email: "E-posta",
    location: "Konum",
    web: "Proje",
    copy: "Kopyala",
    copied: "Kopyalandı",
    footer: "Murat Can Başkan · Uzakyol Baş Mühendisi",
    photoNote: "Gemi fotoğrafları temsilidir; bazıları üçüncü taraf kaynaklara aittir.",
  },
  en: {
    htmlTitle: "Murat Can Başkan — Ocean-Going Chief Engineer | bskn.tr",
    description:
      "Murat Can Başkan, Ocean-Going Chief Engineer. In the engine room since 2007: tankers, bulk carriers, capesize, Ro-Ro, powerships; ME-B and ME-C new-builds.",
    ogTitle: "Murat Can Başkan — Ocean-Going Chief Engineer",
    skip: "Skip to content",
    nav: { career: "Career", fleet: "Fleet", skills: "Expertise", credentials: "Credentials", contact: "Contact" },
    navLabel: "Sections",
    langLabel: "Language",
    themeToDark: "Switch to dark theme",
    themeToLight: "Switch to light theme",
    cv: "Download CV",
    cvLong: "Download CV — PDF",
    heroKicker: "Ocean-Going Chief Engineer · ITU Maritime YDO’06",
    heroLead: (years: number, posts: number) =>
      `${years} years in the engine room. From product tanker to capesize, from steam turbine to ME-C — ${posts} posts, one discipline.`,
    heroCareer: "See the career",
    currentLabel: "Current post",
    statsLabel: "By the numbers",
    bmmsKicker: "The project I am building",
    bmmsLink: "BMMS project page",
    careerKicker: "Logbook",
    careerTitle: (start: number) => `From ${start} to today`,
    careerHint: "Filter by vessel type.",
    filterLabel: "Filter by vessel type",
    now: "Now",
    shown: (n: number) => `Showing ${n} posts`,
    fleetKicker: "Fleet",
    fleetTitle: "Vessel and plant types worked",
    skillsKicker: "Expertise",
    skillsTitle: "What the engine room asks for",
    credKicker: "Credentials",
    credTitle: "Certificates and training",
    pending: "Certificate pending",
    memberTitle: "Memberships",
    eduTitle: "Education",
    langTitle: "Languages",
    contactKicker: "Contact",
    contactTitle: "Let’s talk about the next voyage.",
    contactSub: "For posts, consultancy and technical collaboration.",
    phone: "Phone",
    email: "Email",
    location: "Location",
    web: "Project",
    copy: "Copy",
    copied: "Copied",
    footer: "Murat Can Başkan · Ocean-Going Chief Engineer",
    photoNote: "Vessel photos are representative; some belong to third-party sources.",
  },
} as const;

export type Copy = (typeof COPY)[Lang];
export const copyFor = (lang: Lang): Copy => COPY[lang];
